### ISSUE TITLE
Display the randomly selected recipe suggestion on the screen

### ISSUE THREAD

**Issue by OrestisBollano** [sopra-fs23-group-03/sopra-fs23-group-03-client#17]

**Comment by chiaralentsch** [comment]
16aeec7b0a4ef1a4491d230ea58957da8c052c67
5f41cc828f73f5e04c0321ec4fd7bb9949046010
a952bdeeca6ef2fcb5efa6086b6394db5578d6ee
3e4c8f4f033855735921a8d70d7f0424f2f5766a
